---
title: "Enriched and Depleted Proteins"
author: "Ryan Wong"
date: "2023-06-23"
output: html_document
---

## Load Packages

```{r}

library(tidyverse)
library(ggplot2)
library(dplyr)
library(tibble)
library(ggrepel)
library(imputeLCMD)
library(writexl)

```

## Load Data

```{r}
prot <- read.delim("Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/Normalized_curated_Prot_Quant.txt")
rownames(prot) <- prot[,1]
p.imp <- impute.MinProb(prot[1:nrow(prot), 3:ncol(prot)], q = 0.05, tune.sigma = 0.05)
prot <- cbind(prot[,1:2], p.imp)
t.prot <- as.data.frame(t(prot[3:ncol(prot)]))

```

## Subset into strains

```{r}
#Set list of names to title new dataframes

Strains <- c("n05", "A14", "BY4741", "CBS6223", "CCY_97", "CCY_98", "CL324_2", "CL549", "CL564", "CL649", "CL650", "CL655", "CLI_21", "D1", "DB1122", "DB1374", "DB1714", "DB4317", "SM8", "UWOPS", "Y6_b")

#Generate subset dataframes

n <- 1
while (n < 22) {
  x <- subset(t.prot, t.prot[,4023] == n)
  x <- as.data.frame(t(x))
  assign(Strains[n], x)
  
  #Convert to log2
  x.l <- log2(x[1:(nrow(x)-1),])
  assign(paste(Strains[n], "_log2", sep = ""), x.l)
  
  n <- n + 1
}

t.prot <- as.data.frame(t(t.prot[,1:(ncol(t.prot)-1)]))

```

## T-tests & log2 Fold-change

```{r}

#Set list to pull datatable names from

S <-c("n05", "A14", "CBS6223", "CCY_97", "CCY_98", "CL324_2", "CL549", "CL564", "CL649", "CL650", "CL655", "CLI_21", "D1", "DB1122", "DB1374", "DB1714", "DB4317", "SM8", "UWOPS", "Y6_b")

S_log <- c("n05_log2", "A14_log2", "CBS6223_log2", "CCY_97_log2", "CCY_98_log2", "CL324_2_log2", "CL549_log2", "CL564_log2", "CL649_log2", "CL650_log2", "CL655_log2", "CLI_21_log2", "D1_log2", "DB1122_log2", "DB1374_log2", "DB1714_log2", "DB4317_log2", "SM8_log2", "UWOPS_log2", "Y6_b_log2")

#Run T-tests and calculate log2 fold-change

n <- 1

for (r in unique(S_log)) {
  
  pval <- c()

for (i in unique(rownames(t.prot))) {

  pval.fil <- get(S_log[n]) %>%

    filter(rownames(get(S_log[n])) == i)

  ref <- BY4741 %>%
    
    filter(rownames(BY4741) == i)

  ref.fil <- BY4741_log2 %>%
    
    filter(rownames(BY4741_log2) == i)

 test <- get(S[n]) %>%

    filter(rownames(get(S[n])) == i)

  test.fil <- get(S_log[n]) %>%

    filter(rownames(get(S_log[n])) == i)

  a <- length(which(!is.na(ref[,2:ncol(ref)])))

  b <- length(which(!is.na(test[,2:ncol(test)])))

 #Change value that a & b must be greater or equal to for more or less minimum IDs
  if (a >= 2 & b >= 2) {

    t <- t.test(ref[,2:ncol(ref)], test[,2:ncol(test)],var.equal = FALSE, alternative = "two.sided", na.action = FALSE)

  pval.fil$ref.mn[i] <- rowMeans(ref[,2:ncol(ref)], na.rm = TRUE)
  pval.fil$test.mn[i] <- rowMeans(test[,2:ncol(test)], na.rm = TRUE)
  pval.fil$pvalue[i] <- t$p.value
  pval.fil$ref.log2.mn[i] <- rowMeans(ref.fil[,2:ncol(ref.fil)], na.rm = TRUE)
  pval.fil$test.log2.mn[i] <- rowMeans(test.fil[,2:ncol(test.fil)], na.rm = TRUE)
  pval.fil$log2_F_C[i] <- log2((pval.fil$test.mn / pval.fil$ref.mn))

  } else {

    pval.fil$ref.mn[i] <- NA
    pval.fil$test.mn[i] <- NA
    pval.fil$pvalue[i] <- NA
    pval.fil$ref.mn[i] <- NA
    pval.fil$test.mn[i] <- NA
    pval.fil$log2_F_C[i] <- NA

  }
  
  pval <- rbind(pval, pval.fil)
  
}

pval$BH <- p.adjust(pval$pvalue, method="BH")
  
pval$DifEx <- "No"
pval$DifEx[pval$log2_F_C > log2(2) & pval$BH < 0.05] <- "Up" # Define enriched protein
pval$DifEx[pval$log2_F_C < log2(0.5) & pval$BH < 0.05] <- "Down" # Define depleted protein
pval$IDs <- prot[1:(nrow(prot)-1),2]

# Retrieve names of only enriched and depleted proteins and place in a column for easy retrieval
pval$gene <- NA
pval$gene[pval$DifEx != "No"] <- pval$IDs[pval$DifEx != "No"]

# Export data
write_xlsx(pval, path = paste("Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/RW091/Cur_Norm_2-fold_BH005_MinProb/", S[n], "_vs_BY4741_BH005.xlsx", sep = ""))

n <- n+1

}

```