---
title: "Intensity Correlation Plots"
author: "Ryan Wong"
date: "2024-08-19"
output: html_document
---

## Load Packages

```{r}

library(ggplot2)
library(dplyr)
library(readxl)
library(stats)

```

## Parameters

```{r}

save_plots <- T

```

## Load Data

```{r}

int <- read_xlsx("Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/RW105 Correlation heatmap/Correlation Intensities.xlsx")

int$IntB <- log10(int$IntB) #convert BY4741 average intensities into log10
int$IntC <- log10(int$IntC) #convert CLIB655 average intensities into log10
int$IntCL <- log10(int$IntCL) #convert CLI_21 average intensities into log10

```

## Plot Density

```{r}

BvC <- int %>%
  ggplot(aes(x=IntB, y=IntC)) +
    geom_point(size = 1, color = "forestgreen")+
    theme_classic()+
  xlab("Log10 Mean BY4741 Intensity") + ylab("Log10 Mean CLIB655 Intensity")

BvC

if(save_plots == T) {
  
ggsave(paste("BY4741 vs CLIB655", ".jpg", sep = ""), device = "jpg", path = "Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/RW105 Correlation heatmap", units = "cm", width = 10, height = 10, dpi = 600)

ggsave(paste("BY4741 vs CLIB655", ".svg", sep = ""), device = "svg", path = "Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/RW105 Correlation heatmap", units = "cm", width = 10, height = 10, dpi = 600)

}

BvCL <- int %>%
  ggplot(aes(x=IntB, y=IntCL)) +
    geom_point(size = 1, color = "forestgreen")+
    theme_classic()+
  xlab("Log10 Mean BY4741 Intensity") + ylab("Log10 Mean CLI_21 Intensity")

BvCL

if(save_plots == T) {
  
ggsave(paste("BY4741 vs CLI_21", ".jpg", sep = ""), device = "jpg", path = "Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/RW105 Correlation heatmap", units = "cm", width = 10, height = 10, dpi = 600)

ggsave(paste("BY4741 vs CLI_21", ".svg", sep = ""), device = "svg", path = "Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/RW105 Correlation heatmap", units = "cm", width = 10, height = 10, dpi = 600)

}

CvCL <- int %>%
  ggplot(aes(x=IntC, y=IntCL)) +
    geom_point(size = 1, color = "forestgreen")+
    theme_classic()+
  xlab("Log10 Mean CLIB655 Intensity") + ylab("Log10 Mean CLI_21 Intensity")

CvCL

if(save_plots == T) {
  
ggsave(paste("CLIB655 vs CLI_21", ".jpg", sep = ""), device = "jpg", path = "Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/RW105 Correlation heatmap", units = "cm", width = 10, height = 10, dpi = 600)

ggsave(paste("CLIB655 vs CLI_21", ".svg", sep = ""), device = "svg", path = "Z:/mayor_lab/USERS/RyanWong/Yeast MS/96-Samples/RW105 Correlation heatmap", units = "cm", width = 10, height = 10, dpi = 600)

}

```

## Person Correlation

```{r}

BC <- cor.test(int$IntB, int$IntC, method = "pearson") #Correlation of BY4741 to CLIB655

BCL <- cor.test(int$IntB, int$IntCL, method = "pearson") #Correlation of BY4741 to CLI_21

CCL <- cor.test(int$IntC, int$IntCL, method = "pearson") #Correlation of CLIB655 to CLI_21

```