---
title: "Presence Absence Table"
author: "Ryan Wong"
date: "2024-06-10"
output: html_document
---

# Library

```{r}

library(readxl)
library(writexl)

```

## Set parameters

```{r}

direct <- "D:/"

run_thresh <- T

thresh <- 10 #Minimum number of strains a protein needs to be depleted in to subset out of 20

```


# Data Loading

```{r}

#De-duplicated list of all depleted proteins (generated manually from files created by "Enriched and Depleted Proteins.Rmd" with all proteins in a single column)
d1 <- read_xlsx(path = "D:/Cur_BH005_Dep_Dedup.xlsx")

#Table of each strain's depleted proteins (generated manually from files created by "Enriched and Depleted Proteins.Rmd" with each strain and its depleted proteins in its own column)
d2 <- read_xlsx(path = "D:/Cur_BH005_Depleted_Table.xlsx")

#De-duplicated list of all enriched proteins (generated manually from files created by "Enriched and Depleted Proteins.Rmd" with all proteins in a single column)
u1 <- read_xlsx(path = "D:/Cur_BH005_Enr_Dedup.xlsx")

#Table of each strain's enriched proteins (generated manually from files created by "Enriched and Depleted Proteins.Rmd" with each strain and its depleted proteins in its own column)
u2 <- read_xlsx(path = "D:/Cur_BH005_Enriched_Table.xlsx")

```

# Tabulation for Presence/Absence tables

```{r}

for (r in unique(d1)){
  
  d1$`n05` <- 0
  d1$`n05`[d1$Proteins %in% d2$`n05`] <- -1
  
  d1$`A14` <- 0
  d1$`A14`[d1$Proteins %in% d2$`A14`] <- -1
  
  d1$`CBS6223` <- 0
  d1$`CBS6223`[d1$Proteins %in% d2$`CBS6223`] <- -1
  
  d1$`CCY_97` <- 0
  d1$`CCY_97`[d1$Proteins %in% d2$`CCY_97`] <- -1
  
  d1$`CCY_98` <- 0
  d1$`CCY_98`[d1$Proteins %in% d2$`CCY_98`] <- -1
  
  d1$`CL324_2` <- 0
  d1$`CL324_2`[d1$Proteins %in% d2$`CL324_2`] <- -1
  
  d1$`CL549` <- 0
  d1$`CL549`[d1$Proteins %in% d2$`CL549`] <- -1
  
  d1$`CL564` <- 0
  d1$`CL564`[d1$Proteins %in% d2$`CL564`] <- -1
  
  d1$`CL649` <- 0
  d1$`CL649`[d1$Proteins %in% d2$`CL649`] <- -1
  
  d1$`CL650` <- 0
  d1$`CL650`[d1$Proteins %in% d2$`CL650`] <- -1
  
  d1$`CL655` <- 0
  d1$`CL655`[d1$Proteins %in% d2$`CL655`] <- -1
  
  d1$`CLI_21` <- 0
  d1$`CLI_21`[d1$Proteins %in% d2$`CLI_21`] <- -1
  
  d1$`D1` <- 0
  d1$`D1`[d1$Proteins %in% d2$`D1`] <- -1
  
  d1$`DB1122` <- 0
  d1$`DB1122`[d1$Proteins %in% d2$`DB1122`] <- -1
  
  d1$`DB1374` <- 0
  d1$`DB1374`[d1$Proteins %in% d2$`DB1374`] <- -1
  
  d1$`DB1714` <- 0
  d1$`DB1714`[d1$Proteins %in% d2$`DB1714`] <- -1
  
  d1$`DB4317` <- 0
  d1$`DB4317`[d1$Proteins %in% d2$`DB4317`] <- -1
  
  d1$`SM8` <- 0
  d1$`SM8`[d1$Proteins %in% d2$`SM8`] <- -1
  
  d1$`UWOPS` <- 0
  d1$`UWOPS`[d1$Proteins %in% d2$`UWOPS`] <- -1
  
  d1$`Y6_b` <- 0
  d1$`Y6_b`[d1$Proteins %in% d2$`Y6_b`] <- -1
  
}

for (i in unique(u1)){
  
  u1$`n05` <- 0
  u1$`n05`[u1$Proteins %in% u2$`n05`] <- 1
  
  u1$`A14` <- 0
  u1$`A14`[u1$Proteins %in% u2$`A14`] <- 1
  
  u1$`CBS6223` <- 0
  u1$`CBS6223`[u1$Proteins %in% u2$`CBS6223`] <- 1
  
  u1$`CCY_97` <- 0
  u1$`CCY_97`[u1$Proteins %in% u2$`CCY_97`] <- 1
  
  u1$`CCY_98` <- 0
  u1$`CCY_98`[u1$Proteins %in% u2$`CCY_98`] <- 1
  
  u1$`CL324_2` <- 0
  u1$`CL324_2`[u1$Proteins %in% u2$`CL324_2`] <- 1
  
  u1$`CL549` <- 0
  u1$`CL549`[u1$Proteins %in% u2$`CL549`] <- 1
  
  u1$`CL564` <- 0
  u1$`CL564`[u1$Proteins %in% u2$`CL564`] <- 1
  
  u1$`CL649` <- 0
  u1$`CL649`[u1$Proteins %in% u2$`CL649`] <- 1
  
  u1$`CL650` <- 0
  u1$`CL650`[u1$Proteins %in% u2$`CL650`] <- 1
  
  u1$`CL655` <- 0
  u1$`CL655`[u1$Proteins %in% u2$`CL655`] <- 1
  
  u1$`CLI_21` <- 0
  u1$`CLI_21`[u1$Proteins %in% u2$`CLI_21`] <- 1
  
  u1$`D1` <- 0
  u1$`D1`[u1$Proteins %in% u2$`D1`] <- 1
  
  u1$`DB1122` <- 0
  u1$`DB1122`[u1$Proteins %in% u2$`DB1122`] <- 1
  
  u1$`DB1374` <- 0
  u1$`DB1374`[u1$Proteins %in% u2$`DB1374`] <- 1
  
  u1$`DB1714` <- 0
  u1$`DB1714`[u1$Proteins %in% u2$`DB1714`] <- 1
  
  u1$`DB4317` <- 0
  u1$`DB4317`[u1$Proteins %in% u2$`DB4317`] <- 1
  
  u1$`SM8` <- 0
  u1$`SM8`[u1$Proteins %in% u2$`SM8`] <- 1
  
  u1$`UWOPS` <- 0
  u1$`UWOPS`[u1$Proteins %in% u2$`UWOPS`] <- 1
  
  u1$`Y6_b` <- 0
  u1$`Y6_b`[u1$Proteins %in% u2$`Y6_b`] <- 1
  
  }

```

# Occurance Totals

```{r}

# Sum the number of strains a protein is enriched or depleted in
d1$sum <- rowSums(d1[,2:21])

u1$sum <- rowSums(u1[,2:21])

# Make Presence/Absence tables for the enriched and depleted proteins (1 for significantly enriched, -1 for significantly depleted, 0 for neither)
write_xlsx(d1, path = paste0(direct, "/Cur_BH005_Dep_PA_Table.xlsx"))

write_xlsx(u1, path = paste0(direct, "/Cur_BH005_Enr_PA_Table.xlsx"))

```

# Subset by Occurance Threshold

```{r}

if (run_thresh == T) {

  dThresh <- subset(d1, sum <= -thresh) # Select protein if depleted in the same or greater number of strains as the threshold set above

  uThresh <- subset(u1, sum >= thresh) # Select protein if enriched in the same or greater number of strains as the threshold set above

  write_xlsx(dThresh, path = paste0(direct, "/", thresh, "_Depleted_Table.xlsx"))

  write_xlsx(uThresh, path = paste0(direct, "/", thresh,"_Enriched_Table.xlsx"))

}

```